build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          VISUAL_VERSIONS: "14"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          VISUAL_VERSIONS: "15"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/

test_script:
  - python build.py
