FROM microsoft/windowsservercore:10.0.14393.2485

LABEL maintainer="Luis Martinez de Bartolome <luism@jfrog.com>"

RUN choco install --no-progress --yes vcbuildtools --version=2015.4 -ia "/Full"
RUN RefreshEnv