version: '3'
services:
    gcc5:
        build:
            context: gcc_5
            dockerfile: Dockerfile
            args:
                CONAN_VERSION: ${DOCKER_BUILD_TAG}
                CMAKE_VERSION: ${CMAKE_VERSION}
                CMAKE_VERSION_FULL: ${CMAKE_VERSION_FULL}
                PYTHON_VERSION: ${PYTHON_VERSION}
                PYTHON_VERSION_FULL: ${PYTHON_VERSION_FULL}
        image: "${DOCKER_USERNAME}/gcc5:${DOCKER_BUILD_TAG}"
        container_name: gcc5
        tty: true
    gcc7:
        build:
            context: gcc_7
            dockerfile: Dockerfile
            args:
                CONAN_VERSION: ${DOCKER_BUILD_TAG}
                CMAKE_VERSION: ${CMAKE_VERSION}
                CMAKE_VERSION_FULL: ${CMAKE_VERSION_FULL}
                PYTHON_VERSION: ${PYTHON_VERSION}
                PYTHON_VERSION_FULL: ${PYTHON_VERSION_FULL}
        image: "${DOCKER_USERNAME}/gcc7:${DOCKER_BUILD_TAG}"
        container_name: gcc7
        tty: true
    gcc9:
        build:
            context: gcc_9
            dockerfile: Dockerfile
            args:
                CONAN_VERSION: ${DOCKER_BUILD_TAG}
                CMAKE_VERSION: ${CMAKE_VERSION}
                CMAKE_VERSION_FULL: ${CMAKE_VERSION_FULL}
                PYTHON_VERSION: ${PYTHON_VERSION}
                PYTHON_VERSION_FULL: ${PYTHON_VERSION_FULL}
        image: "${DOCKER_USERNAME}/gcc9:${DOCKER_BUILD_TAG}"
        container_name: gcc9
        tty: true
    gcc5-jenkins:
        depends_on:
            - gcc5
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc5:${DOCKER_BUILD_TAG}
                CONAN_VERSION: ${DOCKER_BUILD_TAG}
                AGENT_VERSION: ${JENKINS_AGENT_VERSION}
                JAVA_JDK_VERSION: ${JAVA_JDK_VERSION}
        image: "${DOCKER_USERNAME}/gcc5-jenkins:${DOCKER_BUILD_TAG}-${JENKINS_AGENT_VERSION}"
        container_name: gcc5-jenkins
    gcc7-jenkins:
        depends_on:
            - gcc7
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc7:${DOCKER_BUILD_TAG}
                CONAN_VERSION: ${DOCKER_BUILD_TAG}
                AGENT_VERSION: ${JENKINS_AGENT_VERSION}
                JAVA_JDK_VERSION: ${JAVA_JDK_VERSION}
        image: "${DOCKER_USERNAME}/gcc7-jenkins:${DOCKER_BUILD_TAG}-${JENKINS_AGENT_VERSION}"
        container_name: gcc7-jenkins
    gcc9-jenkins:
        depends_on:
            - gcc9
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc9:${DOCKER_BUILD_TAG}
                CONAN_VERSION: ${DOCKER_BUILD_TAG}
                AGENT_VERSION: ${JENKINS_AGENT_VERSION}
                JAVA_JDK_VERSION: ${JAVA_JDK_VERSION}
        image: "${DOCKER_USERNAME}/gcc9-jenkins:${DOCKER_BUILD_TAG}-${JENKINS_AGENT_VERSION}"
        container_name: gcc9-jenkins
